version: "3.1"

services:
  boer-naar-burger-api-webserver:
    image: nginx:alpine
    restart: always
    container_name: boer-naar-burger-api-webserver
    working_dir: /application
    volumes:
      - ../:/application
      - ./images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8090:80
    depends_on:
      - boer-naar-burger-api-php-fpm

  boer-naar-burger-api-php-fpm:
    build: ./images/php-fpm
    restart: always
    container_name: boer-naar-burger-api-php-fpm
    working_dir: /application
    volumes:
      - ../:/application
